peekaboo-image-picker/src/iosMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.ios.kt

- Refactored the `picker` function within `rememberImagePickerLauncher` to ensure synchronized handling of multiple image data loading. This change guarantees that all selected images are processed and loaded correctly.
- Made necessary adjustments to ensure that the `onResult` callback provides a complete and accurate list of the selected `byteArrays` after all images are fully loaded.
close #12

[fix/ios-multiple-image-selection-concurrency] Resolve Concurrency Issue in iOS Multiple Image Picker

---

gradle/libs.versions.toml
peekaboo-camera/build.gradle.kts
peekaboo-camera/src/androidMain/AndroidManifest.xml
peekaboo-camera/src/androidMain/kotlin/com/preat/peekaboo/camera/CameraCaptureLauncher.android.kt
peekaboo-camera/src/androidMain/kotlin/com/preat/peekaboo/camera/UuidGenerator.android.kt
peekaboo-camera/src/androidMain/res/xml/path_provider.xml
peekaboo-camera/src/commonMain/kotlin/com/preat/peekaboo/camera/CameraCaptureLauncher.kt
peekaboo-camera/src/commonMain/kotlin/com/preat/peekaboo/camera/UuidGenerator.kt
peekaboo-camera/src/iosMain/kotlin/com/preat/peekaboo/camera/CameraCaptureLauncher.ios.kt
peekaboo-camera/src/iosMain/kotlin/com/preat/peekaboo/camera/UuidGenerator.ios.kt
sample/common/build.gradle.kts
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/App.kt
sample/ios/peekaboo.xcodeproj/project.pbxproj
sample/ios/peekaboo/peekabooApp.swift
settings.gradle.kts

This pull request introduces the `peekaboo-camera` module to the project, providing a unified camera capture functionality across iOS and Android platforms.
- Added the `peekaboo-camera` module to the project.
- Implemented `rememberCameraCaptureLauncher` for both iOS and Android.
- However, it currently does not fully function on iOS. #15
close #9

[feature/add-peekaboo-camera-module] Support Camera Integration for Image Selection

---

convention-plugins/src/main/kotlin/root.publication.gradle.kts
peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/PeekabooCamera.android.kt
peekaboo-ui/src/commonMain/kotlin/com/preat/peekaboo/ui/CameraMode.kt
peekaboo-ui/src/commonMain/kotlin/com/preat/peekaboo/ui/PeekabooCamera.kt
peekaboo-ui/src/iosMain/kotlin/com/preat/peekaboo/ui/PeekabooCamera.ios.kt
sample/android/src/main/AndroidManifest.xml
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/App.kt
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/icon/IconWarning.kt
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/style/Palette.kt
sample/ios/peekaboo.xcodeproj/project.pbxproj

- Added `permissionDeniedContent` parameter to `PeekabooCamera` composable.
- Implemented a usage example in the sample app, showcasing how to use `permissionDeniedContent`.
- Updated the image UI size in the sample app for better layout presentation.
The `permissionDeniedContent` is a composable lambda that gets invoked within the `PeekabooCamera` scope when camera permission is denied. This parameter allows developers to define custom UI elements like informative text, images, or a button to redirect users to settings. If not used, the `PeekabooCamera` composable will render a empty screen when permission is denied. Therefore, it's recommended to implement this feature for a comprehensive user experience.

[feature/add-permission-denied-content] Add `permissionDeniedContent` parameter to `PeekabooCamera` composable

---

.github/workflows/iosBuild.yml

[feature/add-ios-ci-script] Add iOS CI Script

---

.github/workflows/ci_check.yml

- This PR updates the CI workflow to ignore changes in Markdown files, thereby preventing unnecessary CI runs for documentation updates.

[feature/add-ci-ignore-md] Ignore Markdown Files in CI Workflow

---

README.md
convention-plugins/src/main/kotlin/root.publication.gradle.kts
peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.android.kt
peekaboo-image-picker/src/commonMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.kt
peekaboo-image-picker/src/iosMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.ios.kt
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/App.kt

[feature/add-image-resizing-option] Add Image Resizing Options to Image Picker

---

peekaboo-ui/src/androidMain/AndroidManifest.xml

**Issues Resolved:**  [ #31 ]
This pull request specifically addresses the **INSTALL_FAILED_CONFLICTING_PROVIDER** issue, allowing for a smoother installation process. The changes made ensure that the library can be implemented in multiple projects without encountering conflicting provider errors, and installations across different apps on the same device are now error-free.
**Changes Made:**
- Replaced hardcoded package name with applicationId in the manifest file of **peekaboo-ui**.
**Benefits:**
- Resolves the **INSTALL_FAILED_CONFLICTING_PROVIDER** issue.
- Enhances compatibility for implementing the library in multiple projects.

[Fix] Resolved INSTALL_FAILED_CONFLICTING_PROVIDER issue

---

convention-plugins/src/main/kotlin/root.publication.gradle.kts
peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.android.kt
peekaboo-image-picker/src/commonMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.kt
peekaboo-image-picker/src/iosMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.ios.kt

Modified the `launch()` in `ImagePickerLauncher` method to check the `isPhotoPickerActive` flag. If the picker is active in Android, it prevents further executions of `onLaunch()`.

[fix/image-picker-launcher-duplicate-call-prevention] Implement duplicate call prevention in ImagePickerLauncher(Android)

---

peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.android.kt
peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/PeekabooBitmapCache.kt

close #35 
- `PeekabooBitmapCache`: Implemented a new singleton class `PeekabooBitmapCache` to handle memory caching of bitmap images in Android. This class utilizes an `LruCache` to store and retrieve bitmap images efficiently, optimizing memory usage for image picking.
- `Memory Cache Size Calculation`: Implemented a method within `PeekabooBitmapCache` to calculate the optimal cache size based on the available runtime memory. The cache size is set to `25%` of the maximum available memory, with a minimum threshold of 1MB, and this `25%` allocation is inspired by the memory caching policy used in the [qdsfdhvh/compose-imageloader](https://github.com/qdsfdhvh/compose-imageloader) project.

[feature/optimize-memory-cache] Implementation of Memory Cache Optimization for Image Picking in Android

---

peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.android.kt
peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/PeekabooImageResizer.kt

- Separated image resizing logic into the `PeekabooImageResizer` object, ensuring a more modular and maintainable codebase.
- Implemented asynchronous processing using Kotlin coroutines for efficient handling of image resizing tasks in Android.

[feature/async-image-resizer] Enhance Image Processing with Async Methods in Android

---

peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/PeekabooImageResizer.kt

Apply 'IO' Dispatcher for Cache Operations and 'Default' for Image Resizing in Android

[refactor/change_dispatcher] Apply 'IO' Dispatcher for Cache Operations and 'Default' for Image Resizing in Android

---

peekaboo-image-picker/src/iosMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.ios.kt

- Modified the `UIImage.fitInto` function to ensure the original aspect ratio of images is maintained during resizing on iOS.
close #44

[fix/ios-image-aspect-ratio] Maintain Aspect Ratio for Image Resizing on iOS

---

README.md
convention-plugins/src/main/kotlin/root.publication.gradle.kts
peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.android.kt
peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/PeekabooImageResizer.kt
peekaboo-image-picker/src/commonMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.kt
peekaboo-image-picker/src/iosMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.ios.kt

- Modified the `ResizeOptions` data class to include a `resizeThresholdBytes` field, with a default value of 1MB represented in bytes.
- Updated the image resizing logic in the `PeekabooImageResizer` (Android) and `UIImage.fitInto` extension function (iOS) to check the file size against the `resizeThresholdBytes` threshold.
close #50

[feature/resize-based-on-image-size] Implement Image Resizing Based on Image Size Threshold

---

peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/PeekabooImageResizer.kt

- use 'use' extension function to release resource safe
```kotlin
@InlineOnly
public inline fun <T : Closeable?, R> T.use(block: (T) -> R): R {
contract {
callsInPlace(block, InvocationKind.EXACTLY_ONCE)
}
var exception: Throwable? = null
try {
return block(this)
} catch (e: Throwable) {
exception = e
throw e
} finally {
when {
apiVersionIsAtLeast(1, 1, 0) -> this.closeFinally(exception)
this == null -> {}
exception == null -> close()
else ->
try {
close()
} catch (closeException: Throwable) {
// cause.addSuppressed(closeException) // ignored here
}
}
}
}
```

[refactor/use-extension-function] Refactor 'getImageSize' function

---

gradle/libs.versions.toml
peekaboo-image-picker/build.gradle.kts
peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.android.kt
peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/PeekabooImageResizer.kt
peekaboo-image-picker/src/commonMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.kt
peekaboo-image-picker/src/iosMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.ios.kt
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/App.kt

Adding compression quality as parameter of ResizeOption. Fixes #41

Adding compression quality as parameter of ResizeOption. Fixes #41.

---

peekaboo-ui/src/iosMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCameraState.ios.kt

Implemented the missing logic in the `capture()` method to correctly set `isCapturing` to true and invoke the `triggerCaptureAnchor` in `PeekabooCameraState.ios.kt`

[fix/camera-capture-ios] Fix Capture Functionality Not Triggering in iOS

---

peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCamera.android.kt

Fixing #71 - size of overlay containing capture and convert icons to match parent, so that modifier passed for the button is applied correctly (mainly for alignment of buttons)

Fixing #71 - size of overlay containing capture and convert icons to match parent size

---

peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCameraState.android.kt
peekaboo-ui/src/iosMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCameraState.ios.kt

When during recomposition onCapture lambda is recreating, PeekabooCameraState is recreating too. There is bug with state's isCapturing, isCameraReady, cameraMode is set to default values after creating new PeekabooCameraState. Now onCapture does not affect state recreating, it sets as new onCapture callback in PeekabooCameraState.
P.S. fix in 0.5.0 - remember onCapture lambda.

Fix PeekabooCameraState recreation when lambda onCapture does not memoized

---

peekaboo-image-picker/src/iosMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.ios.kt

- Fixed an issue where images below the resize threshold did not have filters applied in iOS

Fixed Issue with Applying Filters to Images Below Threshold Size on iOS

---

build.gradle.kts
convention-plugins/src/main/kotlin/module.publication.gradle.kts
convention-plugins/src/main/kotlin/root.publication.gradle.kts
peekaboo-image-picker/build.gradle.kts
peekaboo-image-picker/src/androidMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.android.kt
peekaboo-image-picker/src/commonMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.kt
peekaboo-image-picker/src/iosMain/kotlin/com/preat/peekaboo/image/picker/ImagePickerLauncher.ios.kt
peekaboo-ui/build.gradle.kts
peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCamera.android.kt
peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/gallery/model/PeekabooMediaImage.kt
peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/gallery/repository/PeekabooGalleryRepository.kt
peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/gallery/viewmodel/PeekabooGalleryViewModel.kt
peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/gallery/viewmodel/PeekabooGalleryViewModelFactory.kt
peekaboo-ui/src/commonMain/kotlin/com/preat/peekaboo/ui/camera/CameraMode.kt
peekaboo-ui/src/commonMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCamera.kt
peekaboo-ui/src/commonMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCameraState.kt
peekaboo-ui/src/commonMain/kotlin/com/preat/peekaboo/ui/gallery/ExperimentalPeekabooGalleryApi.kt
peekaboo-ui/src/commonMain/kotlin/com/preat/peekaboo/ui/gallery/PeekabooGallery.kt
peekaboo-ui/src/iosMain/kotlin/com/preat/peekaboo/ui/camera/CameraAccess.kt
peekaboo-ui/src/iosMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCamera.ios.kt
peekaboo-ui/src/iosMain/kotlin/com/preat/peekaboo/ui/gallery/PeekabooGallery.ios.kt
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/App.kt
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/component/CircularButton.kt
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/component/InstagramCameraButton.kt
settings.gradle.kts

Spotless updates the year at the head of your license based on the year of your last commit.
```bash
./gradlew spotlessApply -PspotlessSetLicenseHeaderYearsFromGitHistory=true
```
I used this script.

[feature/update-license-header-year] Update year of license header

---

gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

Bump agp to 8.3.2, jetbrains compose to 1.6.2, nexus-publish to 2.0.0, gradle to 8.7

[update/deps] Bump agp to 8.3.2, jetbrains compose to 1.6.2, nexus-publish to 2.0.0, gradle to 8.7

---

peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCamera.android.kt
peekaboo-ui/src/androidMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCameraState.android.kt
peekaboo-ui/src/commonMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCamera.kt
peekaboo-ui/src/commonMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCameraState.kt
peekaboo-ui/src/iosMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCamera.ios.kt
peekaboo-ui/src/iosMain/kotlin/com/preat/peekaboo/ui/camera/PeekabooCameraState.ios.kt
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/App.kt
sample/common/src/commonMain/kotlin/com/preat/peekaboo/common/component/PeekabooCameraView.kt
sample/ios/peekaboo/Info.plist

I am attempting to implement MLKit into a KMP application, and I need access to each frame from the camera to do Image analysis on it.
Peekaboo currently didn't have any way of exposing this, so this PR adds that feature.
You can pass `onFrame` to any of the peekaboo-ui functions to immediately receive frame data in the form of a `ByteArray` and the timestamp of the frame.
I have tested this on Android and iOS. However I couldn't get the sample in this repository to run on iOS. However I ported this library to my application and can confirm that frame updates work on iOS.

Feature: Add 'onFrame' lambda to capture the current frame of the camera
